### ISSUE TITLE
Navigation goals only publish position, not orientation

### ISSUE THREAD

**Issue by joe28965** [nielstiben/openTCS-NeNa#10]
I have the system setup that I can create points in openTCS. However, if I set an orientation in the location points in openTCS, they aren't included in the pose send to the navigation goal, only the position is.

**Comment by nielstiben** [comment]
Hi,
Orientations are not (yet) implemented in this version of the vehicle driver. The vehicle driver just focuses on coordinates for now.
However, it is a good suggestion and when I have time I'll consider implementing this feature.
