### ISSUE TITLE
Navigation goal is published with a factor 10 difference

### ISSUE THREAD

**Issue by joe28965** [nielstiben/openTCS-NeNa#11]
My point A in openTCS is set to 3000mm and -2000mm, however the message that is published to ROS 2 is 0.3m and -0.2m, 3000mm should be 3m, not 0.3m. Somewhere in the code is a factor 10 difference

**Comment by butchamon** [comment]
The plant model is in mm, all coordinates from the agv are in meter.
In the vehicle config file the scaling factor should be set to 1.0
file /home/agv/opentcs/openTCS-NeNa-5.0.0-RELEASE_2.0-bin/openTCS-NeNa-Kernel/config/opentcs-kernel-defaults-custom.properties
ros2.adapter.plantModelScale = 1.0

Don't know if this is the proper way but at least it solved the issue on our side.
