### ISSUE TITLE
How many maximum number of vehicle can connect to OpenTCS

### ISSUE THREAD

**Issue by akashpawar9595** [nielstiben/openTCS-NeNa#15]
Hello,
May I know how many numbers of the maximum number of vehicle can connect to opentcs

**Comment by wilcobonestroo** [comment]
Basically, this is not specific to this bridge between ROS 2 and OpenTCS. However, the [documentation from OpenTCS](https://www.opentcs.org/docs/5.2/faq.html) states: 

> There is virtually no limit imposed by the design of the software. The hardware equipment used (CPU, RAM, communication bandwidth etc.) can, however, limit the system’s effective performance.
