### ISSUE TITLE
how can i get the map.yml

### ISSUE THREAD

**Issue by naiveZhou** [nielstiben/openTCS-NeNa#18]
Hi，Your video tutorials work really well，I have completed the basic environment configuration
But I can't find this file in the video.Can you tell where to get it from?
![image](https://user-images.githubusercontent.com/18117945/187011888-9a34a331-4231-43f0-a71b-62bd7ba25052.png)

![image](https://user-images.githubusercontent.com/18117945/187009784-c419d929-c130-411e-9f5f-c882cb9ed767.png)

**Comment by naiveZhou** [comment]
I get it

**Comment by Maroon-hub** [comment]
HOW to link this video tutorials?Please,hlep me ,I need this video tutorials:Preview of an opentcs-ros2 vehicle driver
